slam_toolbox:
  ros__parameters:

    # ROS 2 Çerçeve Ayarları
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_sim_time: true

    # Haritalama Modu
    mode: mapping 

    # Lazer Ayarları
    map_update_interval: 0.5
    resolution: 0.05
    max_laser_range: 15.0
    minimum_time_interval: 0.2
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000
    
    # Teknik Çözücü Ayarları
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None